name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install dependencies
        run: |
          yarn

      - name: Build and deploy
        run: |
          npm run build
          node ./.github/scripts/deploy.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
